services:
  hoit-app:
    image: hoit-app:latest
    container_name: hoit-app
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - redis
      - rabbit-mq
    restart: unless-stopped