spring:
  rabbitmq:
    username: admin
    password: admin
  data:
    redis:
      username: default
      password: 1234
  datasource:
    password: for4000llm
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 99898080219-t1blduds15lqb1lt5a5p13p07jsjlf6f.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
r2:
  endpoint: https://f07373fd866c2022dc69c4cd2218aff2.r2.cloudflarestorage.com/
  access-key: a430d35c83ac671918a733ca24d62022
  secret-key: 39cdcf3e97184769b5ab280d32d4f5bcaccf36b2181d8b056dfe1ea200eefb65
  bucket: hoit-storage
jwt:
  key: afsdkfkjvnxkczjhiafoauw235iu3y64h5tlknfiaidhsfjkasfkjnvsdkjvbagh9y573wytgjierhfgkdsjgjf
  refresh-token:
    expire-time: 604800000
openai:
  api:
    key: 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
piapi:
  api:
    key: 09eaba65e4be89c9d89aeaf51e3e0d55e0becdb876ec57c9bca630a2314d5da9
payment:
  toss:
    secret-key: test_gck_docs_Ovk5rk1EwkEbP0W43n07xlzm
runpod:
  api:
    key: rpa_CRWWTILAOTJAF3O5VKW627U4AU9PZZN4CBOP2ESO6md290